package ru.kpfu.itis.android.asadullin.util

object CountryRepository {
    val list: List<Pair<String, String>> = listOf(
        Pair("Albania", "Tirana"),
        Pair("Andorra", "Andorra la Vella"),
        Pair("Austria", "Vienna"),
        Pair("Belarus", "Minsk"),
        Pair("Belgium", "Brussels"),
        Pair("Vatican City", "Vatican City"),
        Pair("Bulgaria", "Sofia"),
        Pair("Croatia", "Zagreb"),
        Pair("Cyprus", "Nicosia"),
        Pair("Czech Republic", "Prague"),
        Pair("Denmark", "Copenhagen"),
        Pair("Estonia", "Tallinn"),
        Pair("Finland", "Helsinki"),
        Pair("France", "Paris"),
        Pair("Germany", "Berlin"),
        Pair("Greece", "Athens"),
        Pair("Hungary", "Budapest"),
        Pair("Iceland", "Reykjavik"),
        Pair("Ireland", "Dublin"),
        Pair("Italy", "Rome"),
        Pair("Kazakhstan", "Nur-Sultan"),
        Pair("Latvia", "Riga"),
        Pair("Lithuania", "Vilnius"),
        Pair("Liechtenstein", "Vaduz"),
        Pair("Luxembourg", "Luxembourg"),
        Pair("North Macedonia", "Skopje"),
        Pair("Malta", "Valletta"),
        Pair("Moldova", "Chisinau"),
        Pair("Monaco", "Monaco"),
        Pair("Montenegro", "Podgorica"),
        Pair("Netherlands", "Amsterdam"),
        Pair("Norway", "Oslo"),
        Pair("Poland", "Warsaw"),
        Pair("Portugal", "Lisbon"),
        Pair("Romania", "Bucharest"),
        Pair("Russia", "Moscow"),
        Pair("San Marino", "San Marino"),
        Pair("Serbia", "Belgrade"),
        Pair("Slovakia", "Bratislava"),
        Pair("Slovenia", "Ljubljana"),
        Pair("Spain", "Madrid"),
        Pair("Sweden", "Stockholm"),
        Pair("Switzerland", "Bern"),
        Pair("Ukraine", "Kyiv"),
        Pair("United Kingdom", "London")
    )
}
